// apps/angular-demo-app/src/app/task-card/task-card.component.ts
import { CommonModule } from '@angular/common';
import {
    Component,
    EventEmitter,
    HostBinding,
    HostListener,
    Input,
    OnChanges,
    Output,
    SimpleChanges
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Task, TaskPriority, TaskStatus } from '../models';
import { CapitalizePipe, TruncatePipe } from '../pipes';

@Component({
    selector: 'app-task-card',
    standalone: true,
    imports: [CommonModule, FormsModule, TruncatePipe, CapitalizePipe],
    templateUrl: './task-card.component.html',
    styleUrl: './task-card.component.css'
})
export class TaskCardComponent implements OnChanges
{
    @Input() task: Task | null = null;
    @Input() isEditing = false;
    @Input() availableStatuses: TaskStatus[] = [];

    @HostBinding('attr.draggable') draggable = true;
    @HostBinding('class.dragging') isDragging = false;

    @HostListener('dragstart', ['$event'])
    onDragStart(event: DragEvent): void
    {
        if(this.task)
        {
            event.dataTransfer?.setData('text/plain', String(this.task.id));
            this.isDragging = true;
        }
    }

    @HostListener('dragend')
    onDragEnd(): void
    {
        this.isDragging = false;
    }

    editTitle = '';
    editDescription = '';
    editPriority: TaskPriority = 'medium';
    editAssignee = '';
    editDueDate = '';
    showMoveMenu = false;

    @Output() move = new EventEmitter<{ newStatus: TaskStatus }>();
    @Output() delete = new EventEmitter<void>();
    @Output() edit = new EventEmitter<void>();
    @Output() cancelEdit = new EventEmitter<void>();
    @Output() save = new EventEmitter<{ updates: Partial<Task> }>();

    ngOnChanges(changes: SimpleChanges): void
    {
        if((changes['isEditing'] || changes['task']) && this.isEditing && this.task)
        {
            this.editTitle = this.task.title;
            this.editDescription = this.task.description;
            this.editPriority = this.task.priority;
            this.editAssignee = this.task.assignee ?? '';
            this.editDueDate = this.task.dueDate ?? '';
        }
    }

    get priorityClass(): string
    {
        return this.task?.priority ?? 'medium';
    }

    get isOverdue(): boolean
    {
        if(!this.task?.dueDate || this.task.status === 'done') return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate < today;
    }

    get isDueToday(): boolean
    {
        if(!this.task?.dueDate) return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate === today;
    }

    get formattedDueDate(): string
    {
        if(!this.task?.dueDate) return '';
        const date = new Date(this.task.dueDate);
        return date.toLocaleDateString('en-US', {month: 'short', day: 'numeric'});
    }

    getStatusLabel(status: TaskStatus): string
    {
        const labels: Record<TaskStatus, string> = {
            'todo': '📋 To Do', 'in-progress': '🔄 In Progress', 'done': '✅ Done'
        };
        return labels[status];
    }

    onMove(newStatus: TaskStatus): void
    {
        this.showMoveMenu = false;
        this.move.emit({newStatus});
    }

    onDelete(): void
    {
        this.delete.emit();
    }

    onEdit(): void
    {
        this.edit.emit();
    }

    onCancelEdit(): void
    {
        this.cancelEdit.emit();
    }

    onSave(): void
    {
        this.save.emit({
            updates: {
                title: this.editTitle,
                description: this.editDescription,
                priority: this.editPriority,
                assignee: this.editAssignee || null,
                dueDate: this.editDueDate || null
            }
        });
    }

    toggleMoveMenu(): void
    {
        this.showMoveMenu = !this.showMoveMenu;
    }

    setEditPriority(p: TaskPriority): void
    {
        this.editPriority = p;
    }
}

@if (isEditing) {
    <div class="card editing">
        <div class="edit-form">
            <input
                    type="text"
                    class="edit-title"
                    placeholder="Task title"
                    [(ngModel)]="editTitle"
            />

            <textarea
                    class="edit-description"
                    placeholder="Description"
                    [(ngModel)]="editDescription"
            ></textarea>

            <div class="edit-row">
                <span class="edit-label">Priority:</span>
                <div class="priority-buttons">
                    <button
                            class="p-btn low"
                            [class.active]="editPriority === 'low'"
                            (click)="setEditPriority('low')"
                    >Low
                    </button>
                    <button
                            class="p-btn medium"
                            [class.active]="editPriority === 'medium'"
                            (click)="setEditPriority('medium')"
                    >Med
                    </button>
                    <button
                            class="p-btn high"
                            [class.active]="editPriority === 'high'"
                            (click)="setEditPriority('high')"
                    >High
                    </button>
                    <button
                            class="p-btn urgent"
                            [class.active]="editPriority === 'urgent'"
                            (click)="setEditPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="edit-row">
                <label for="edit-assignee">Assignee:</label>
                <input
                        id="edit-assignee"
                        type="text"
                        placeholder="Name"
                        [(ngModel)]="editAssignee"
                />
            </div>

            <div class="edit-row">
                <label for="edit-due-date">Due Date:</label>
                <input
                        id="edit-due-date"
                        type="date"
                        [(ngModel)]="editDueDate"
                />
            </div>

            <div class="edit-actions">
                <button class="save-btn" (click)="onSave()">💾 Save</button>
                <button class="cancel-btn" (click)="onCancelEdit()">Cancel</button>
            </div>
        </div>
    </div>
} @else {
    <div class="card" [class.overdue]="isOverdue">
        <div class="card-header">
            <span class="priority-indicator {{ priorityClass }}"></span>
            <div class="card-actions">
                <button class="action-btn" (click)="toggleMoveMenu()" title="Move">↔️</button>
                <button class="action-btn" (click)="onEdit()" title="Edit">✏️</button>
                <button class="action-btn delete" (click)="onDelete()" title="Delete">🗑️</button>
            </div>
        </div>

        @if (showMoveMenu) {
            <div class="move-menu">
                @for (status of availableStatuses; track status) {
                    <button class="move-option" (click)="onMove(status)">
                        {{ getStatusLabel(status) }}
                    </button>
                }
            </div>
        }

        <h3 class="card-title">{{ task?.title | uppercase }}</h3>

        @if (task?.description) {
            <p class="card-description">{{ task?.description | truncate:80 }}</p>
        }

        <div class="card-meta">
            @if (task?.tags?.length) {
                <div class="tags">
                    @for (tag of task?.tags; track tag) {
                        <span class="tag">{{ tag | lowercase | capitalize }}</span>
                    }
                </div>
            }

            <div class="meta-row">
                @if (task?.assignee) {
                    <span class="assignee">👤 {{ task?.assignee }}</span>
                }

                @if (task?.dueDate) {
                    <span class="due-date" [class.overdue]="isOverdue" [class.today]="isDueToday">
            📅 {{ formattedDueDate }}
                        @if (isOverdue) {
                            <span class="overdue-badge">Overdue!</span>
                        }
                        @if (isDueToday) {
                            <span class="today-badge">Today</span>
                        }
          </span>
                }
            </div>
        </div>
    </div>
}

// apps/fluff-demo-app/src/app/task-card.component.ts
import type { OnDestroy, Subscription } from '@fluffjs/fluff';
import { Component, HostBinding, HostListener, Input, Output, Publisher, Reactive } from '@fluffjs/fluff';
import type { Task, TaskPriority, TaskStatus } from './models.js';

@Component({
    selector: 'task-card',
    templateUrl: './task-card.component.html',
    styleUrl: './task-card.component.css'
})
export class TaskCardComponent extends HTMLElement implements OnDestroy
{
    @Input() public task: Task | null = null;
    @Input() public isEditing = false;
    @Input() public availableStatuses: TaskStatus[] = [];

    @HostBinding('attr.draggable') public override draggable = true;
    @HostBinding('class.dragging') public isDragging = false;

    @HostListener('dragstart')
    public onDragStart(event: DragEvent): void
    {
        if (this.task)
        {
            event.dataTransfer?.setData('text/plain', String(this.task.id));
            this.isDragging = true;
        }
    }

    @HostListener('dragend')
    public onDragEnd(): void
    {
        this.isDragging = false;
    }

    @Reactive() public editTitle = '';
    @Reactive() public editDescription = '';
    @Reactive() public editPriority: TaskPriority = 'medium';
    @Reactive() public editAssignee = '';
    @Reactive() public editDueDate = '';
    @Reactive() public showMoveMenu = false;

    @Output() public move = new Publisher<{ newStatus: TaskStatus }>();
    @Output() public delete = new Publisher<void>();
    @Output() public edit = new Publisher<void>();
    @Output() public cancelEdit = new Publisher<void>();
    @Output() public save = new Publisher<{ updates: Partial<Task> }>();

    private readonly _watchEditing: Subscription = this.$watch(['isEditing', 'task'], () =>
    {
        if (this.isEditing && this.task)
        {
            this.editTitle = this.task.title;
            this.editDescription = this.task.description;
            this.editPriority = this.task.priority;
            this.editAssignee = this.task.assignee ?? '';
            this.editDueDate = this.task.dueDate ?? '';
        }
    });

    public get priorityClass(): string
    {
        return this.task?.priority ?? 'medium';
    }

    public get isOverdue(): boolean
    {
        if (!this.task?.dueDate || this.task.status === 'done') return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate < today;
    }

    public get isDueToday(): boolean
    {
        if (!this.task?.dueDate) return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate === today;
    }

    public get formattedDueDate(): string
    {
        if (!this.task?.dueDate) return '';
        const date = new Date(this.task.dueDate);
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }

    public getStatusLabel(status: TaskStatus): string
    {
        const labels: Record<TaskStatus, string> = {
            'todo': '📋 To Do', 'in-progress': '🔄 In Progress', 'done': '✅ Done'
        };
        return labels[status];
    }

    public onMove(newStatus: TaskStatus): void
    {
        this.showMoveMenu = false;
        this.move.emit({ newStatus });
    }

    public onDelete(): void
    {
        this.delete.emit();
    }

    public onEdit(): void
    {
        this.edit.emit();
    }

    public onCancelEdit(): void
    {
        this.cancelEdit.emit();
    }

    public onSave(): void
    {
        this.save.emit({
            updates: {
                title: this.editTitle,
                description: this.editDescription,
                priority: this.editPriority,
                assignee: this.editAssignee || null,
                dueDate: this.editDueDate || null
            }
        });
    }

    public toggleMoveMenu(): void
    {
        this.showMoveMenu = !this.showMoveMenu;
    }

    public setEditPriority(p: TaskPriority): void
    {
        this.editPriority = p;
    }

    public onDestroy(): void
    {
        this._watchEditing.unsubscribe();
    }
}

@if (isEditing) {
    <div class="card editing">
        <div class="edit-form">
            <input
                    type="text"
                    class="edit-title"
                    placeholder="Task title"
                    [value]="editTitle"
                    (input)="editTitle = $event.target.value"
            />

            <textarea
                    class="edit-description"
                    placeholder="Description"
                    [value]="editDescription"
                    (input)="editDescription = $event.target.value"
            ></textarea>

            <div class="edit-row">
                <label>Priority:</label>
                <div class="priority-buttons">
                    <button
                            class="p-btn low"
                            [class.active]="editPriority === 'low'"
                            (click)="setEditPriority('low')"
                    >Low
                    </button>
                    <button
                            class="p-btn medium"
                            [class.active]="editPriority === 'medium'"
                            (click)="setEditPriority('medium')"
                    >Med
                    </button>
                    <button
                            class="p-btn high"
                            [class.active]="editPriority === 'high'"
                            (click)="setEditPriority('high')"
                    >High
                    </button>
                    <button
                            class="p-btn urgent"
                            [class.active]="editPriority === 'urgent'"
                            (click)="setEditPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="edit-row">
                <label>Assignee:</label>
                <input
                        type="text"
                        placeholder="Name"
                        [value]="editAssignee"
                        (input)="editAssignee = $event.target.value"
                />
            </div>

            <div class="edit-row">
                <label>Due Date:</label>
                <input
                        type="date"
                        [value]="editDueDate"
                        (input)="editDueDate = $event.target.value"
                />
            </div>

            <div class="edit-actions">
                <button class="save-btn" (click)="onSave()">💾 Save</button>
                <button class="cancel-btn" (click)="onCancelEdit()">Cancel</button>
            </div>
        </div>
    </div>
} @else {
    <div class="card" [class.overdue]="isOverdue">
        <div class="card-header">
            <span class="priority-indicator {{ priorityClass }}"></span>
            <div class="card-actions">
                <button class="action-btn" (click)="toggleMoveMenu()" title="Move">↔️</button>
                <button class="action-btn" (click)="onEdit()" title="Edit">✏️</button>
                <button class="action-btn delete" (click)="onDelete()" title="Delete">🗑️</button>
            </div>
        </div>

        @if (showMoveMenu) {
            <div class="move-menu">
                @for (status of availableStatuses; track status) {
                    <button class="move-option" (click)="onMove(status)">
                        {{ getStatusLabel(status) }}
                    </button>
                }
            </div>
        }

        <h3 class="card-title">{{ task.title | uppercase }}</h3>

        @if (task.description) {
            <p class="card-description">{{ task.description | truncate:80 }}</p>
        }

        <div class="card-meta">
            @if (task.tags.length > 0) {
                <div class="tags">
                    @for (tag of task.tags; track tag) {
                        <span class="tag">{{ tag | lowercase | capitalize }}</span>
                    }
                </div>
            }

            <div class="meta-row">
                @if (task.assignee) {
                    <span class="assignee">👤 {{ task.assignee }}</span>
                }

                @if (task.dueDate) {
                    <span class="due-date" [class.overdue]="isOverdue" [class.today]="isDueToday">
            📅 {{ task.dueDate | date:'short' }}
                        @if (isOverdue) {
                            <span class="overdue-badge">Overdue!</span>
                        }
                        @if (isDueToday) {
                            <span class="today-badge">Today</span>
                        }
          </span>
                }
            </div>
        </div>
    </div>
}
