// apps/angular-demo-app/src/app/task-form/task-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, ElementRef, EventEmitter, Output, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { TaskPriority } from '../models';

@Component({
    selector: 'app-task-form',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './task-form.component.html',
    styleUrl: './task-form.component.css'
})
export class TaskFormComponent
{
    @ViewChild('titleInput') titleInputEl!: ElementRef<HTMLInputElement>;

    isExpanded = false;
    taskTitle = '';
    description = '';
    priority: TaskPriority = 'medium';
    tagsInput = '';

    @Output() submitTask = new EventEmitter<{
        title: string;
        description: string;
        priority: TaskPriority;
        tags: string[]
    }>();

    get parsedTags(): string[]
    {
        return this.tagsInput
            .split(',')
            .map(t => t.trim())
            .filter(t => t.length > 0);
    }

    toggleForm(): void
    {
        this.isExpanded = !this.isExpanded;
        if (!this.isExpanded)
        {
            this.resetForm();
        }
    }

    focusTitleTemplateRef(input: HTMLInputElement): void
    {
        input.focus();
    }

    focusTitleViewChild(): void
    {
        this.titleInputEl?.nativeElement?.focus();
    }

    handleSubmit(): void
    {
        if (!this.taskTitle.trim()) return;

        this.submitTask.emit({
            title: this.taskTitle.trim(),
            description: this.description.trim(),
            priority: this.priority,
            tags: this.parsedTags
        });

        this.resetForm();
        this.isExpanded = false;
    }

    setPriority(p: TaskPriority): void
    {
        this.priority = p;
    }

    private resetForm(): void
    {
        this.taskTitle = '';
        this.description = '';
        this.priority = 'medium';
        this.tagsInput = '';
    }
}

<div class="form-wrapper">
    <button class="add-btn" (click)="toggleForm()">
        @if (isExpanded) {
            ✕ Cancel
        } @else {
            + New Task
        }
    </button>

    @if (isExpanded) {
        <div class="form-panel">
            <div class="form-group">
                <label for="task-title">Title *</label>
                <input
                    #titleInput
                    id="task-title"
                    type="text"
                    placeholder="What needs to be done?"
                    [(ngModel)]="taskTitle"
                    (keyup.enter)="handleSubmit()"
                />
            </div>

            <div class="form-group">
                <label for="task-description">Description</label>
                <textarea
                        id="task-description"
                        placeholder="Add more details..."
                        [(ngModel)]="description"
                ></textarea>
            </div>

            <div class="form-group">
                <span class="form-label">Priority</span>
                <div class="priority-selector">
                    <button
                            class="priority-btn low"
                            [class.selected]="priority === 'low'"
                            (click)="setPriority('low')"
                    >Low
                    </button>
                    <button
                            class="priority-btn medium"
                            [class.selected]="priority === 'medium'"
                            (click)="setPriority('medium')"
                    >Medium
                    </button>
                    <button
                            class="priority-btn high"
                            [class.selected]="priority === 'high'"
                            (click)="setPriority('high')"
                    >High
                    </button>
                    <button
                            class="priority-btn urgent"
                            [class.selected]="priority === 'urgent'"
                            (click)="setPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="form-group">
                <label for="task-tags">Tags (comma-separated)</label>
                <input
                        id="task-tags"
                        type="text"
                        placeholder="frontend, bug, feature..."
                        [(ngModel)]="tagsInput"
                />
                @if (parsedTags.length > 0) {
                    <div class="tag-preview">
                        @for (tag of parsedTags; track tag) {
                            <span class="tag">{{ tag }}</span>
                        }
                    </div>
                }
            </div>

            <button class="submit-btn" (click)="handleSubmit()">
                Create Task
            </button>
            <button class="submit-btn" (click)="focusTitleTemplateRef(titleInput)">
                Focus Title (Template Ref)
            </button>
            <button class="submit-btn" (click)="focusTitleViewChild()">
                Focus Title (ViewChild)
            </button>
        </div>
    }
</div>

// apps/fluff-demo-app/src/app/task-form.component.ts
import { Component, Output, Publisher, Reactive, ViewChild } from '@fluffjs/fluff';
import type { TaskPriority } from './models.js';

@Component({
    selector: 'task-form', templateUrl: './task-form.component.html', styleUrl: './task-form.component.css'
})
export class TaskFormComponent extends HTMLElement
{
    @ViewChild('titleInput') public titleInputEl!: HTMLInputElement;

    @Reactive() public isExpanded = false;
    @Reactive() public taskTitle = '';
    @Reactive() public description = '';
    @Reactive() public priority: TaskPriority = 'medium';
    @Reactive() public tagsInput = '';

    @Reactive() public status = 0;

    @Output() public submit = new Publisher<{
        title: string;
        description: string;
        priority: TaskPriority;
        tags: string[]
    }>();

    public get parsedTags(): string[]
    {
        return this.tagsInput
            .split(',')
            .map(t => t.trim())
            .filter(t => t.length > 0);
    }

    public toggleForm(): void
    {
        this.isExpanded = !this.isExpanded;
        if (!this.isExpanded)
        {
            this._resetForm();
        }
    }

    public increment(): void
    {
        this.status++;
        if (this.status > 3)
        {
            this.status = 0;
        }
    }

    public focusTitle(input: HTMLInputElement): void
    {
        input.focus();
    }

    public focusTitleViewChild(input: HTMLInputElement): void
    {
        this.titleInputEl.focus();
    }

    public handleSubmit(): void
    {
        if (!this.taskTitle.trim()) return;

        this.submit.emit({
            title: this.taskTitle.trim(),
            description: this.description.trim(),
            priority: this.priority,
            tags: this.parsedTags
        });

        this._resetForm();
        this.isExpanded = false;
    }

    public setPriority(p: TaskPriority): void
    {
        this.priority = p;
    }

    private _resetForm(): void
    {
        this.taskTitle = '';
        this.description = '';
        this.priority = 'medium';
        this.tagsInput = '';
    }
}

<div class="form-wrapper">
    <button class="add-btn" (click)="toggleForm()">
        @if (isExpanded) {
            ✕ Cancel
        } @else {
            + New Task
        }
    </button>

    @if (isExpanded) {
        <div class="form-panel">
            <div class="form-group">
                <label>Title *</label>
                <input
                    #titleInput
                    type="text"
                    placeholder="What needs to be done?"
                    [value]="taskTitle"
                    (input)="taskTitle = $event.target.value"
                    (keyup.enter)="handleSubmit()"
                />
            </div>

            <div class="form-group">
                <label>Description</label>
                <textarea
                        placeholder="Add more details..."
                        [value]="description"
                        (input)="description = $event.target.value"
                ></textarea>
            </div>

            <div class="form-group">
                <label>Priority</label>
                <div class="priority-selector">
                    <button
                            class="priority-btn low"
                            [class.selected]="priority === 'low'"
                            (click)="setPriority('low')"
                    >Low
                    </button>
                    <button
                            class="priority-btn medium"
                            [class.selected]="priority === 'medium'"
                            (click)="setPriority('medium')"
                    >Medium
                    </button>
                    <button
                            class="priority-btn high"
                            [class.selected]="priority === 'high'"
                            (click)="setPriority('high')"
                    >High
                    </button>
                    <button
                            class="priority-btn urgent"
                            [class.selected]="priority === 'urgent'"
                            (click)="setPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="form-group">
                <label>Tags (comma-separated)</label>
                <input
                        type="text"
                        placeholder="frontend, bug, feature..."
                        [value]="tagsInput"
                        (input)="tagsInput = $event.target.value"
                />
                @if (parsedTags.length > 0) {
                    <div class="tag-preview">
                        @for (tag of parsedTags; track tag) {
                            <span class="tag">{{ tag }}</span>
                        }
                    </div>
                }
            </div>

            <button class="submit-btn" (click)="handleSubmit()">
                Create Task
            </button>
            <button class="submit-btn" (click)="focusTitle(titleInput)">
                Focus Title (Template Ref)
            </button>
            <button class="submit-btn" (click)="focusTitleViewChild(titleInput)">
                Focus Title (ViewChild)
            </button>
        </div>
    }
</div>
