// apps/fluff-demo-app/src/app/kanban-column.component.ts
import { Component, HostBinding, HostListener, Input, Output, Publisher } from '@fluffjs/fluff';
import type { Column, Task, TaskStatus } from './models.js';

@Component({
    selector: 'kanban-column', templateUrl: './kanban-column.component.html', styleUrl: './kanban-column.component.css'
})
export class KanbanColumnComponent extends HTMLElement
{
    @Input() public column: Column = { id: 'todo', title: 'To Do', color: '#e74c3c' };
    @Input() public tasks: Task[] = [];
    @Input() public editingTaskId: number | null = null;

    @HostBinding('class.drag-over') public isDragOver = false;

    @HostBinding('attr.data-column-id') public get columnId(): string
    {
        return this.column.id;
    }

    @HostListener('dragover')
    public onDragOver(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = true;
    }

    @HostListener('dragleave')
    public onDragLeave(): void
    {
        this.isDragOver = false;
    }

    @HostListener('drop')
    public onDrop(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = false;
        const taskId = event.dataTransfer?.getData('text/plain');
        if (taskId)
        {
            this.moveTask.emit({ taskId: Number(taskId), newStatus: this.column.id })
                .catch(console.error);
        }
    }

    @Output() public moveTask = new Publisher<{ taskId: number; newStatus: TaskStatus }>();
    @Output() public deleteTask = new Publisher<{ taskId: number }>();
    @Output() public startEdit = new Publisher<{ taskId: number }>();
    @Output() public cancelEdit = new Publisher<void>();
    @Output() public saveEdit = new Publisher<{ taskId: number; updates: Partial<Task> }>();

    public get taskCount(): number
    {
        return this.tasks.length;
    }

    public get availableStatuses(): TaskStatus[]
    {
        const all: TaskStatus[] = ['todo', 'in-progress', 'done'];
        return all.filter(s => s !== this.column.id);
    }

    public onMoveTask(taskId: number, newStatus: TaskStatus): void
    {
        this.moveTask.emit({ taskId, newStatus })
            .catch(console.error);
    }

    public onDeleteTask(taskId: number): void
    {
        this.deleteTask.emit({ taskId })
            .catch(console.error);
    }

    public onStartEdit(taskId: number): void
    {
        this.startEdit.emit({ taskId })
            .catch(console.error);
    }

    public onCancelEdit(): void
    {
        this.cancelEdit.emit()
            .catch(console.error);
    }

    public onSaveEdit(taskId: number, updates: Partial<Task>): void
    {
        this.saveEdit.emit({ taskId, updates })
            .catch(console.error);
    }
}
<div class="column">
    <div class="column-header" [style.border-color]="column.color">
        <h2>{{ column.title }}</h2>
        <span class="count">{{ taskCount }}</span>
    </div>

    <div class="task-list">
        @for (task of tasks; track task.id) {
            <task-card
                    [task]="task"
                    [isEditing]="editingTaskId === task.id"
                    [availableStatuses]="availableStatuses"
                    (move)="onMoveTask(task.id, $event.newStatus)"
                    (delete)="onDeleteTask(task.id)"
                    (edit)="onStartEdit(task.id)"
                    (cancelEdit)="onCancelEdit()"
                    (save)="onSaveEdit(task.id, $event.updates)"
            ></task-card>
        }

        @if (tasks.length === 0) {
            <div class="empty-column">
                <span>No tasks</span>
            </div>
        }
    </div>
</div>

// apps/angular-demo-app/src/app/kanban-column/kanban-column.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, HostBinding, HostListener, Input, Output } from '@angular/core';
import type { Column, Task, TaskStatus } from '../models';
import { TaskCardComponent } from '../task-card/task-card.component';

@Component({
    selector: 'app-kanban-column',
    standalone: true,
    imports: [CommonModule, TaskCardComponent],
    templateUrl: './kanban-column.component.html',
    styleUrl: './kanban-column.component.css'
})
export class KanbanColumnComponent
{
    @Input() column: Column = { id: 'todo', title: 'To Do', color: '#e74c3c' };
    @Input() tasks: Task[] = [];
    @Input() editingTaskId: number | null = null;

    @HostBinding('class.drag-over') isDragOver = false;

    @HostBinding('attr.data-column-id') get columnId(): string
    {
        return this.column.id;
    }

    @HostListener('dragover', ['$event'])
    onDragOver(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = true;
    }

    @HostListener('dragleave')
    onDragLeave(): void
    {
        this.isDragOver = false;
    }

    @HostListener('drop', ['$event'])
    onDrop(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = false;
        const taskId = event.dataTransfer?.getData('text/plain');
        if (taskId)
        {
            this.moveTask.emit({ taskId: Number(taskId), newStatus: this.column.id });
        }
    }

    @Output() moveTask = new EventEmitter<{ taskId: number; newStatus: TaskStatus }>();
    @Output() deleteTask = new EventEmitter<{ taskId: number }>();
    @Output() startEdit = new EventEmitter<{ taskId: number }>();
    @Output() cancelEdit = new EventEmitter<void>();
    @Output() saveEdit = new EventEmitter<{ taskId: number; updates: Partial<Task> }>();

    get taskCount(): number
    {
        return this.tasks.length;
    }

    get availableStatuses(): TaskStatus[]
    {
        const all: TaskStatus[] = ['todo', 'in-progress', 'done'];
        return all.filter(s => s !== this.column.id);
    }

    onMoveTask(taskId: number, newStatus: TaskStatus): void
    {
        this.moveTask.emit({ taskId, newStatus });
    }

    onDeleteTask(taskId: number): void
    {
        this.deleteTask.emit({ taskId });
    }

    onStartEdit(taskId: number): void
    {
        this.startEdit.emit({ taskId });
    }

    onCancelEdit(): void
    {
        this.cancelEdit.emit();
    }

    onSaveEdit(taskId: number, updates: Partial<Task>): void
    {
        this.saveEdit.emit({ taskId, updates });
    }
}

<div class="column">
    <div class="column-header" [style.border-color]="column.color">
        <h2>{{ column.title }}</h2>
        <span class="count">{{ taskCount }}</span>
    </div>

    <div class="task-list">
        @for (task of tasks; track task.id) {
            <app-task-card
                    [task]="task"
                    [isEditing]="editingTaskId === task.id"
                    [availableStatuses]="availableStatuses"
                    (move)="onMoveTask(task.id, $event.newStatus)"
                    (delete)="onDeleteTask(task.id)"
                    (edit)="onStartEdit(task.id)"
                    (cancelEdit)="onCancelEdit()"
                    (save)="onSaveEdit(task.id, $event.updates)"
            ></app-task-card>
        }

        @if (tasks.length === 0) {
            <div class="empty-column">
                <span>No tasks</span>
            </div>
        }
    </div>
</div>
