// apps/angular-demo-app/src/app/kanban-column/kanban-column.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, HostBinding, HostListener, Input, Output } from '@angular/core';
import type { Column, Task, TaskStatus } from '../models';
import { TaskCardComponent } from '../task-card/task-card.component';

@Component({
    selector: 'app-kanban-column',
    standalone: true,
    imports: [CommonModule, TaskCardComponent],
    templateUrl: './kanban-column.component.html',
    styleUrl: './kanban-column.component.css'
})
export class KanbanColumnComponent
{
    @Input() column: Column = { id: 'todo', title: 'To Do', color: '#e74c3c' };
    @Input() tasks: Task[] = [];
    @Input() editingTaskId: number | null = null;

    @HostBinding('class.drag-over') isDragOver = false;

    @HostBinding('attr.data-column-id') get columnId(): string
    {
        return this.column.id;
    }

    @HostListener('dragover', ['$event'])
    onDragOver(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = true;
    }

    @HostListener('dragleave')
    onDragLeave(): void
    {
        this.isDragOver = false;
    }

    @HostListener('drop', ['$event'])
    onDrop(event: DragEvent): void
    {
        event.preventDefault();
        this.isDragOver = false;
        const taskId = event.dataTransfer?.getData('text/plain');
        if (taskId)
        {
            this.moveTask.emit({ taskId: Number(taskId), newStatus: this.column.id });
        }
    }

    @Output() moveTask = new EventEmitter<{ taskId: number; newStatus: TaskStatus }>();
    @Output() deleteTask = new EventEmitter<{ taskId: number }>();
    @Output() startEdit = new EventEmitter<{ taskId: number }>();
    @Output() cancelEdit = new EventEmitter<void>();
    @Output() saveEdit = new EventEmitter<{ taskId: number; updates: Partial<Task> }>();

    get taskCount(): number
    {
        return this.tasks.length;
    }

    get availableStatuses(): TaskStatus[]
    {
        const all: TaskStatus[] = ['todo', 'in-progress', 'done'];
        return all.filter(s => s !== this.column.id);
    }

    onMoveTask(taskId: number, newStatus: TaskStatus): void
    {
        this.moveTask.emit({ taskId, newStatus });
    }

    onDeleteTask(taskId: number): void
    {
        this.deleteTask.emit({ taskId });
    }

    onStartEdit(taskId: number): void
    {
        this.startEdit.emit({ taskId });
    }

    onCancelEdit(): void
    {
        this.cancelEdit.emit();
    }

    onSaveEdit(taskId: number, updates: Partial<Task>): void
    {
        this.saveEdit.emit({ taskId, updates });
    }
}

<div class="column">
    <div class="column-header" [style.border-color]="column.color">
        <h2>{{ column.title }}</h2>
        <span class="count">{{ taskCount }}</span>
    </div>

    <div class="task-list">
        @for (task of tasks; track task.id) {
            <app-task-card
                    [task]="task"
                    [isEditing]="editingTaskId === task.id"
                    [availableStatuses]="availableStatuses"
                    (move)="onMoveTask(task.id, $event.newStatus)"
                    (delete)="onDeleteTask(task.id)"
                    (edit)="onStartEdit(task.id)"
                    (cancelEdit)="onCancelEdit()"
                    (save)="onSaveEdit(task.id, $event.updates)"
            ></app-task-card>
        }

        @if (tasks.length === 0) {
            <div class="empty-column">
                <span>No tasks</span>
            </div>
        }
    </div>
</div>

// apps/react-demo-app/src/app/components/KanbanColumn.tsx
import { useState } from 'react';
import type { Column, Task, TaskStatus } from '../models';
import { TaskCardComponent } from './TaskCard';
import './KanbanColumn.css';

interface KanbanColumnProps
{
    column: Column;
    tasks: Task[];
    editingTaskId: number | null;
    onMoveTask: (taskId: number, newStatus: TaskStatus) => void;
    onDeleteTask: (taskId: number) => void;
    onStartEdit: (taskId: number) => void;
    onCancelEdit: () => void;
    onSaveEdit: (taskId: number, updates: Partial<Task>) => void;
}

export function KanbanColumnComponent({
                                          column,
                                          tasks,
                                          editingTaskId,
                                          onMoveTask,
                                          onDeleteTask,
                                          onStartEdit,
                                          onCancelEdit,
                                          onSaveEdit
                                      }: KanbanColumnProps)
{
    const [isDragOver, setIsDragOver] = useState(false);

    const availableStatuses: TaskStatus[] = (['todo', 'in-progress', 'done'] as TaskStatus[])
        .filter(s => s !== column.id);

    const handleDragOver = (e: React.DragEvent) =>
    {
        e.preventDefault();
        setIsDragOver(true);
    };

    const handleDragLeave = () =>
    {
        setIsDragOver(false);
    };

    const handleDrop = (e: React.DragEvent) =>
    {
        e.preventDefault();
        setIsDragOver(false);
        const taskId = e.dataTransfer.getData('text/plain');
        if (taskId)
        {
            onMoveTask(Number(taskId), column.id);
        }
    };

    return (
        <div
            className={`kanban-column ${isDragOver ? 'drag-over' : ''}`}
            data-column-id={column.id}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
        >
            <div className="column">
                <div className="column-header" style={{ borderColor: column.color }}>
                    <h2>{column.title}</h2>
                    <span className="count">{tasks.length}</span>
                </div>

                <div className="task-list">
                    {tasks.map((task) => (
                        <TaskCardComponent
                            key={task.id}
                            task={task}
                            isEditing={editingTaskId === task.id}
                            availableStatuses={availableStatuses}
                            onMove={(newStatus) => onMoveTask(task.id, newStatus)}
                            onDelete={() => onDeleteTask(task.id)}
                            onEdit={() => onStartEdit(task.id)}
                            onCancelEdit={onCancelEdit}
                            onSave={(updates) => onSaveEdit(task.id, updates)}
                        />
                    ))}

                    {tasks.length === 0 && (
                        <div className="empty-column">
                            <span>No tasks</span>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
