// apps/angular-demo-app/src/app/task-stats/task-stats.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import type { TaskStats } from '../models';

@Component({
    selector: 'app-task-stats',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './task-stats.component.html',
    styleUrl: './task-stats.component.css'
})
export class TaskStatsComponent implements OnInit, OnDestroy
{
    @Input() stats: TaskStats = {
        total: 0,
        byStatus: {'todo': 0, 'in-progress': 0, 'done': 0},
        byPriority: {'low': 0, 'medium': 0, 'high': 0, 'urgent': 0},
        overdue: 0,
        dueToday: 0
    };

    currentTime = new Date().toLocaleTimeString();

    private intervalId: ReturnType<typeof setInterval> | null = null;

    get completionPercent(): number
    {
        if(this.stats.total === 0) return 0;
        return Math.round((this.stats.byStatus.done / this.stats.total) * 100);
    }

    get urgentAndHighCount(): number
    {
        return this.stats.byPriority.urgent + this.stats.byPriority.high;
    }

    ngOnDestroy(): void
    {
        if(this.intervalId !== null)
        {
            clearInterval(this.intervalId);
        }
    }

    ngOnInit(): void
    {
        this.intervalId = setInterval(() =>
        {
            this.currentTime = new Date().toLocaleTimeString();
        }, 1000);
    }
}

<div class="stats-panel">
    <div class="stat-card completion">
        <div class="stat-icon">✅</div>
        <div class="stat-content">
            <span class="stat-value">{{ completionPercent }}%</span>
            <span class="stat-label">Completed</span>
        </div>
        <div class="progress-bar">
            <div class="progress-fill" [style.width]="completionPercent + '%'"></div>
        </div>
    </div>

    <div class="stat-card status">
        <div class="stat-icon">📋</div>
        <div class="stat-content">
            <div class="stat-row">
                <span class="dot todo"></span>
                <span>To Do: {{ stats.byStatus['todo'] }}</span>
            </div>
            <div class="stat-row">
                <span class="dot in-progress"></span>
                <span>In Progress: {{ stats.byStatus['in-progress'] }}</span>
            </div>
            <div class="stat-row">
                <span class="dot done"></span>
                <span>Done: {{ stats.byStatus['done'] }}</span>
            </div>
        </div>
    </div>

    <div class="stat-card priority">
        <div class="stat-icon">🎯</div>
        <div class="stat-content">
            <span class="stat-value">{{ urgentAndHighCount }}</span>
            <span class="stat-label">High Priority</span>
        </div>
    </div>

    <div class="stat-card alerts">
        <div class="stat-icon">⚠️</div>
        <div class="stat-content">
            @if (stats.overdue > 0) {
                <div class="alert-item overdue">
                    <span class="alert-count">{{ stats.overdue }}</span>
                    <span>Overdue</span>
                </div>
            }
            @if (stats.dueToday > 0) {
                <div class="alert-item due-today">
                    <span class="alert-count">{{ stats.dueToday }}</span>
                    <span>Due Today</span>
                </div>
            }
            @if (stats.overdue === 0 && stats.dueToday === 0) {
                <span class="all-clear">All clear! 🎉</span>
            }
        </div>
    </div>
</div>

// apps/react-demo-app/src/app/components/TaskStats.tsx
import type { TaskStats } from '../models';
import './TaskStats.css';

interface TaskStatsProps
{
    stats: TaskStats;
}

export function TaskStatsComponent({stats}: TaskStatsProps)
{
    const completionPercent = stats.total === 0 ? 0 : Math.round((stats.byStatus.done / stats.total) * 100);
    const urgentAndHighCount = stats.byPriority.urgent + stats.byPriority.high;

    return (
        <div className="stats-panel">
            <div className="stat-card completion">
                <div className="stat-icon">✅</div>
                <div className="stat-content">
                    <span className="stat-value">{completionPercent}%</span>
                    <span className="stat-label">Completed</span>
                </div>
                <div className="progress-bar">
                    <div className="progress-fill" style={{width: `${completionPercent}%`}}></div>
                </div>
            </div>

            <div className="stat-card status">
                <div className="stat-icon">📋</div>
                <div className="stat-content">
                    <div className="stat-row">
                        <span className="dot todo"></span>
                        <span>To Do: {stats.byStatus['todo']}</span>
                    </div>
                    <div className="stat-row">
                        <span className="dot in-progress"></span>
                        <span>In Progress: {stats.byStatus['in-progress']}</span>
                    </div>
                    <div className="stat-row">
                        <span className="dot done"></span>
                        <span>Done: {stats.byStatus['done']}</span>
                    </div>
                </div>
            </div>

            <div className="stat-card priority">
                <div className="stat-icon">🎯</div>
                <div className="stat-content">
                    <span className="stat-value">{urgentAndHighCount}</span>
                    <span className="stat-label">High Priority</span>
                </div>
            </div>

            <div className="stat-card alerts">
                <div className="stat-icon">⚠️</div>
                <div className="stat-content">
                    {stats.overdue > 0 && (
                        <div className="alert-item overdue">
                            <span className="alert-count">{stats.overdue}</span>
                            <span>Overdue</span>
                        </div>
                    )}
                    {stats.dueToday > 0 && (
                        <div className="alert-item due-today">
                            <span className="alert-count">{stats.dueToday}</span>
                            <span>Due Today</span>
                        </div>
                    )}
                    {stats.overdue === 0 && stats.dueToday === 0 && (
                        <span className="all-clear">All clear! 🎉</span>
                    )}
                </div>
            </div>
        </div>
    );
}
