// apps/fluff-demo-app/src/app/task-card.component.ts
import type { OnDestroy, Subscription } from '@fluffjs/fluff';
import { Component, HostBinding, HostListener, Input, Output, Publisher, Reactive } from '@fluffjs/fluff';
import type { Task, TaskPriority, TaskStatus } from './models.js';

@Component({
    selector: 'task-card',
    templateUrl: './task-card.component.html',
    styleUrl: './task-card.component.css'
})
export class TaskCardComponent extends HTMLElement implements OnDestroy
{
    @Input() public task: Task | null = null;
    @Input() public isEditing = false;
    @Input() public availableStatuses: TaskStatus[] = [];

    @HostBinding('attr.draggable') public override draggable = true;
    @HostBinding('class.dragging') public isDragging = false;

    @HostListener('dragstart')
    public onDragStart(event: DragEvent): void
    {
        if (this.task)
        {
            event.dataTransfer?.setData('text/plain', String(this.task.id));
            this.isDragging = true;
        }
    }

    @HostListener('dragend')
    public onDragEnd(): void
    {
        this.isDragging = false;
    }

    @Reactive() public editTitle = '';
    @Reactive() public editDescription = '';
    @Reactive() public editPriority: TaskPriority = 'medium';
    @Reactive() public editAssignee = '';
    @Reactive() public editDueDate = '';
    @Reactive() public showMoveMenu = false;

    @Output() public move = new Publisher<{ newStatus: TaskStatus }>();
    @Output() public delete = new Publisher<void>();
    @Output() public edit = new Publisher<void>();
    @Output() public cancelEdit = new Publisher<void>();
    @Output() public save = new Publisher<{ updates: Partial<Task> }>();

    private readonly _watchEditing: Subscription = this.$watch(['isEditing', 'task'], () =>
    {
        if (this.isEditing && this.task)
        {
            this.editTitle = this.task.title;
            this.editDescription = this.task.description;
            this.editPriority = this.task.priority;
            this.editAssignee = this.task.assignee ?? '';
            this.editDueDate = this.task.dueDate ?? '';
        }
    });

    public get priorityClass(): string
    {
        return this.task?.priority ?? 'medium';
    }

    public get isOverdue(): boolean
    {
        if (!this.task?.dueDate || this.task.status === 'done') return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate < today;
    }

    public get isDueToday(): boolean
    {
        if (!this.task?.dueDate) return false;
        const [today] = new Date().toISOString()
            .split('T');
        return this.task.dueDate === today;
    }

    public get formattedDueDate(): string
    {
        if (!this.task?.dueDate) return '';
        const date = new Date(this.task.dueDate);
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }

    public getStatusLabel(status: TaskStatus): string
    {
        const labels: Record<TaskStatus, string> = {
            'todo': '📋 To Do', 'in-progress': '🔄 In Progress', 'done': '✅ Done'
        };
        return labels[status];
    }

    public onMove(newStatus: TaskStatus): void
    {
        this.showMoveMenu = false;
        this.move.emit({ newStatus });
    }

    public onDelete(): void
    {
        this.delete.emit();
    }

    public onEdit(): void
    {
        this.edit.emit();
    }

    public onCancelEdit(): void
    {
        this.cancelEdit.emit();
    }

    public onSave(): void
    {
        this.save.emit({
            updates: {
                title: this.editTitle,
                description: this.editDescription,
                priority: this.editPriority,
                assignee: this.editAssignee || null,
                dueDate: this.editDueDate || null
            }
        });
    }

    public toggleMoveMenu(): void
    {
        this.showMoveMenu = !this.showMoveMenu;
    }

    public setEditPriority(p: TaskPriority): void
    {
        this.editPriority = p;
    }

    public onDestroy(): void
    {
        this._watchEditing.unsubscribe();
    }
}

@if (isEditing) {
    <div class="card editing">
        <div class="edit-form">
            <input
                    type="text"
                    class="edit-title"
                    placeholder="Task title"
                    [value]="editTitle"
                    (input)="editTitle = $event.target.value"
            />

            <textarea
                    class="edit-description"
                    placeholder="Description"
                    [value]="editDescription"
                    (input)="editDescription = $event.target.value"
            ></textarea>

            <div class="edit-row">
                <label>Priority:</label>
                <div class="priority-buttons">
                    <button
                            class="p-btn low"
                            [class.active]="editPriority === 'low'"
                            (click)="setEditPriority('low')"
                    >Low
                    </button>
                    <button
                            class="p-btn medium"
                            [class.active]="editPriority === 'medium'"
                            (click)="setEditPriority('medium')"
                    >Med
                    </button>
                    <button
                            class="p-btn high"
                            [class.active]="editPriority === 'high'"
                            (click)="setEditPriority('high')"
                    >High
                    </button>
                    <button
                            class="p-btn urgent"
                            [class.active]="editPriority === 'urgent'"
                            (click)="setEditPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="edit-row">
                <label>Assignee:</label>
                <input
                        type="text"
                        placeholder="Name"
                        [value]="editAssignee"
                        (input)="editAssignee = $event.target.value"
                />
            </div>

            <div class="edit-row">
                <label>Due Date:</label>
                <input
                        type="date"
                        [value]="editDueDate"
                        (input)="editDueDate = $event.target.value"
                />
            </div>

            <div class="edit-actions">
                <button class="save-btn" (click)="onSave()">💾 Save</button>
                <button class="cancel-btn" (click)="onCancelEdit()">Cancel</button>
            </div>
        </div>
    </div>
} @else {
    <div class="card" [class.overdue]="isOverdue">
        <div class="card-header">
            <span class="priority-indicator {{ priorityClass }}"></span>
            <div class="card-actions">
                <button class="action-btn" (click)="toggleMoveMenu()" title="Move">↔️</button>
                <button class="action-btn" (click)="onEdit()" title="Edit">✏️</button>
                <button class="action-btn delete" (click)="onDelete()" title="Delete">🗑️</button>
            </div>
        </div>

        @if (showMoveMenu) {
            <div class="move-menu">
                @for (status of availableStatuses; track status) {
                    <button class="move-option" (click)="onMove(status)">
                        {{ getStatusLabel(status) }}
                    </button>
                }
            </div>
        }

        <h3 class="card-title">{{ task.title | uppercase }}</h3>

        @if (task.description) {
            <p class="card-description">{{ task.description | truncate:80 }}</p>
        }

        <div class="card-meta">
            @if (task.tags.length > 0) {
                <div class="tags">
                    @for (tag of task.tags; track tag) {
                        <span class="tag">{{ tag | lowercase | capitalize }}</span>
                    }
                </div>
            }

            <div class="meta-row">
                @if (task.assignee) {
                    <span class="assignee">👤 {{ task.assignee }}</span>
                }

                @if (task.dueDate) {
                    <span class="due-date" [class.overdue]="isOverdue" [class.today]="isDueToday">
            📅 {{ task.dueDate | date:'short' }}
                        @if (isOverdue) {
                            <span class="overdue-badge">Overdue!</span>
                        }
                        @if (isDueToday) {
                            <span class="today-badge">Today</span>
                        }
          </span>
                }
            </div>
        </div>
    </div>
}

// apps/react-demo-app/src/app/components/TaskCard.tsx
import { useEffect, useState } from 'react';
import type { Task, TaskPriority, TaskStatus } from '../models';
import './TaskCard.css';

interface TaskCardProps
{
    task: Task;
    isEditing: boolean;
    availableStatuses: TaskStatus[];
    onMove: (newStatus: TaskStatus) => void;
    onDelete: () => void;
    onEdit: () => void;
    onCancelEdit: () => void;
    onSave: (updates: Partial<Task>) => void;
}

export function TaskCardComponent({
                                      task,
                                      isEditing,
                                      availableStatuses,
                                      onMove,
                                      onDelete,
                                      onEdit,
                                      onCancelEdit,
                                      onSave
                                  }: TaskCardProps)
{
    const [isDragging, setIsDragging] = useState(false);
    const [editTitle, setEditTitle] = useState('');
    const [editDescription, setEditDescription] = useState('');
    const [editPriority, setEditPriority] = useState<TaskPriority>('medium');
    const [editAssignee, setEditAssignee] = useState('');
    const [editDueDate, setEditDueDate] = useState('');
    const [showMoveMenu, setShowMoveMenu] = useState(false);

    useEffect(() =>
    {
        if (isEditing && task)
        {
            setEditTitle(task.title);
            setEditDescription(task.description);
            setEditPriority(task.priority);
            setEditAssignee(task.assignee ?? '');
            setEditDueDate(task.dueDate ?? '');
        }
    }, [isEditing, task]);

    const priorityClass = task.priority;

    const today = new Date().toISOString()
        .split('T')[0];
    const isOverdue = task.dueDate && task.dueDate < today && task.status !== 'done';
    const isDueToday = task.dueDate === today;

    const formattedDueDate = task.dueDate
        ? new Date(task.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
        : '';

    const getStatusLabel = (status: TaskStatus): string =>
    {
        const labels: Record<TaskStatus, string> = {
            'todo': '📋 To Do',
            'in-progress': '🔄 In Progress',
            'done': '✅ Done'
        };
        return labels[status];
    };

    const handleDragStart = (e: React.DragEvent) =>
    {
        e.dataTransfer.setData('text/plain', String(task.id));
        setIsDragging(true);
    };

    const handleDragEnd = () =>
    {
        setIsDragging(false);
    };

    const handleSave = () =>
    {
        onSave({
            title: editTitle,
            description: editDescription,
            priority: editPriority,
            assignee: editAssignee || null,
            dueDate: editDueDate || null
        });
    };

    const capitalize = (str: string) => str.charAt(0)
        .toUpperCase() + str.slice(1)
        .toLowerCase();
    const truncate = (str: string, len: number) => str.length > len ? str.slice(0, len) + '...' : str;

    if (isEditing)
    {
        return (
            <div className={`task-card ${isDragging ? 'dragging' : ''}`}>
                <div className="card editing">
                    <div className="edit-form">
                        <input
                            type="text"
                            className="edit-title"
                            placeholder="Task title"
                            value={editTitle}
                            onChange={(e) => setEditTitle(e.target.value)}
                        />

                        <textarea
                            className="edit-description"
                            placeholder="Description"
                            value={editDescription}
                            onChange={(e) => setEditDescription(e.target.value)}
                        ></textarea>

                        <div className="edit-row">
                            <label>Priority:</label>
                            <div className="priority-buttons">
                                <button
                                    className={`p-btn low ${editPriority === 'low' ? 'active' : ''}`}
                                    onClick={() => setEditPriority('low')}
                                >Low
                                </button>
                                <button
                                    className={`p-btn medium ${editPriority === 'medium' ? 'active' : ''}`}
                                    onClick={() => setEditPriority('medium')}
                                >Med
                                </button>
                                <button
                                    className={`p-btn high ${editPriority === 'high' ? 'active' : ''}`}
                                    onClick={() => setEditPriority('high')}
                                >High
                                </button>
                                <button
                                    className={`p-btn urgent ${editPriority === 'urgent' ? 'active' : ''}`}
                                    onClick={() => setEditPriority('urgent')}
                                >Urgent
                                </button>
                            </div>
                        </div>

                        <div className="edit-row">
                            <label>Assignee:</label>
                            <input
                                type="text"
                                placeholder="Name"
                                value={editAssignee}
                                onChange={(e) => setEditAssignee(e.target.value)}
                            />
                        </div>

                        <div className="edit-row">
                            <label>Due Date:</label>
                            <input
                                type="date"
                                value={editDueDate}
                                onChange={(e) => setEditDueDate(e.target.value)}
                            />
                        </div>

                        <div className="edit-actions">
                            <button className="save-btn" onClick={handleSave}>💾 Save</button>
                            <button className="cancel-btn" onClick={onCancelEdit}>Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div
            className={`task-card ${isDragging ? 'dragging' : ''}`}
            draggable
            onDragStart={handleDragStart}
            onDragEnd={handleDragEnd}
        >
            <div className={`card ${isOverdue ? 'overdue' : ''}`}>
                <div className="card-header">
                    <span className={`priority-indicator ${priorityClass}`}></span>
                    <div className="card-actions">
                        <button className="action-btn" onClick={() => setShowMoveMenu(!showMoveMenu)} title="Move">↔️
                        </button>
                        <button className="action-btn" onClick={onEdit} title="Edit">✏️</button>
                        <button className="action-btn delete" onClick={onDelete} title="Delete">🗑️</button>
                    </div>
                </div>

                {showMoveMenu && (
                    <div className="move-menu">
                        {availableStatuses.map((status) => (
                            <button
                                key={status}
                                className="move-option"
                                onClick={() =>
                                {
                                    setShowMoveMenu(false);
                                    onMove(status);
                                }}
                            >
                                {getStatusLabel(status)}
                            </button>
                        ))}
                    </div>
                )}

                <h3 className="card-title">{task.title.toUpperCase()}</h3>

                {task.description && (
                    <p className="card-description">{truncate(task.description, 80)}</p>
                )}

                <div className="card-meta">
                    {task.tags.length > 0 && (
                        <div className="tags">
                            {task.tags.map((tag) => (
                                <span key={tag} className="tag">{capitalize(tag.toLowerCase())}</span>
                            ))}
                        </div>
                    )}

                    <div className="meta-row">
                        {task.assignee && (
                            <span className="assignee">👤 {task.assignee}</span>
                        )}

                        {task.dueDate && (
                            <span className={`due-date ${isOverdue ? 'overdue' : ''} ${isDueToday ? 'today' : ''}`}>
                                📅 {formattedDueDate}
                                {isOverdue && <span className="overdue-badge">Overdue!</span>}
                                {isDueToday && <span className="today-badge">Today</span>}
                            </span>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
