// apps/fluff-demo-app/src/app/task-form.component.ts
import { Component, Output, Publisher, Reactive, ViewChild } from '@fluffjs/fluff';
import type { TaskPriority } from './models.js';

@Component({
    selector: 'task-form', templateUrl: './task-form.component.html', styleUrl: './task-form.component.css'
})
export class TaskFormComponent extends HTMLElement
{
    @ViewChild('titleInput') public titleInputEl!: HTMLInputElement;

    @Reactive() public isExpanded = false;
    @Reactive() public taskTitle = '';
    @Reactive() public description = '';
    @Reactive() public priority: TaskPriority = 'medium';
    @Reactive() public tagsInput = '';

    @Reactive() public status = 0;

    @Output() public submit = new Publisher<{
        title: string;
        description: string;
        priority: TaskPriority;
        tags: string[]
    }>();

    public get parsedTags(): string[]
    {
        return this.tagsInput
            .split(',')
            .map(t => t.trim())
            .filter(t => t.length > 0);
    }

    public toggleForm(): void
    {
        this.isExpanded = !this.isExpanded;
        if (!this.isExpanded)
        {
            this._resetForm();
        }
    }

    public increment(): void
    {
        this.status++;
        if (this.status > 3)
        {
            this.status = 0;
        }
    }

    public focusTitle(input: HTMLInputElement): void
    {
        input.focus();
    }

    public focusTitleViewChild(input: HTMLInputElement): void
    {
        this.titleInputEl.focus();
    }

    public handleSubmit(): void
    {
        if (!this.taskTitle.trim()) return;

        this.submit.emit({
            title: this.taskTitle.trim(),
            description: this.description.trim(),
            priority: this.priority,
            tags: this.parsedTags
        });

        this._resetForm();
        this.isExpanded = false;
    }

    public setPriority(p: TaskPriority): void
    {
        this.priority = p;
    }

    private _resetForm(): void
    {
        this.taskTitle = '';
        this.description = '';
        this.priority = 'medium';
        this.tagsInput = '';
    }
}

<div class="form-wrapper">
    <button class="add-btn" (click)="toggleForm()">
        @if (isExpanded) {
            ✕ Cancel
        } @else {
            + New Task
        }
    </button>

    @if (isExpanded) {
        <div class="form-panel">
            <div class="form-group">
                <label>Title *</label>
                <input
                    #titleInput
                    type="text"
                    placeholder="What needs to be done?"
                    [value]="taskTitle"
                    (input)="taskTitle = $event.target.value"
                    (keyup.enter)="handleSubmit()"
                />
            </div>

            <div class="form-group">
                <label>Description</label>
                <textarea
                        placeholder="Add more details..."
                        [value]="description"
                        (input)="description = $event.target.value"
                ></textarea>
            </div>

            <div class="form-group">
                <label>Priority</label>
                <div class="priority-selector">
                    <button
                            class="priority-btn low"
                            [class.selected]="priority === 'low'"
                            (click)="setPriority('low')"
                    >Low
                    </button>
                    <button
                            class="priority-btn medium"
                            [class.selected]="priority === 'medium'"
                            (click)="setPriority('medium')"
                    >Medium
                    </button>
                    <button
                            class="priority-btn high"
                            [class.selected]="priority === 'high'"
                            (click)="setPriority('high')"
                    >High
                    </button>
                    <button
                            class="priority-btn urgent"
                            [class.selected]="priority === 'urgent'"
                            (click)="setPriority('urgent')"
                    >Urgent
                    </button>
                </div>
            </div>

            <div class="form-group">
                <label>Tags (comma-separated)</label>
                <input
                        type="text"
                        placeholder="frontend, bug, feature..."
                        [value]="tagsInput"
                        (input)="tagsInput = $event.target.value"
                />
                @if (parsedTags.length > 0) {
                    <div class="tag-preview">
                        @for (tag of parsedTags; track tag) {
                            <span class="tag">{{ tag }}</span>
                        }
                    </div>
                }
            </div>

            <button class="submit-btn" (click)="handleSubmit()">
                Create Task
            </button>
            <button class="submit-btn" (click)="focusTitle(titleInput)">
                Focus Title (Template Ref)
            </button>
            <button class="submit-btn" (click)="focusTitleViewChild(titleInput)">
                Focus Title (ViewChild)
            </button>
        </div>
    }
</div>

// apps/react-demo-app/src/app/components/TaskForm.tsx
import { useRef, useState } from 'react';
import type { TaskPriority } from '../models';
import './TaskForm.css';

interface TaskFormProps
{
    onSubmit: (data: { title: string; description: string; priority: TaskPriority; tags: string[] }) => void;
}

export function TaskFormComponent({onSubmit}: TaskFormProps)
{
    const titleInputRef = useRef<HTMLInputElement>(null);

    const [isExpanded, setIsExpanded] = useState(false);
    const [taskTitle, setTaskTitle] = useState('');
    const [description, setDescription] = useState('');
    const [priority, setPriority] = useState<TaskPriority>('medium');
    const [tagsInput, setTagsInput] = useState('');

    const parsedTags = tagsInput
        .split(',')
        .map(t => t.trim())
        .filter(t => t.length > 0);

    const resetForm = () =>
    {
        setTaskTitle('');
        setDescription('');
        setPriority('medium');
        setTagsInput('');
    };

    const toggleForm = () =>
    {
        setIsExpanded(!isExpanded);
        if(isExpanded)
        {
            resetForm();
        }
    };

    const focusTitleTemplateRef = (input: HTMLInputElement | null) =>
    {
        input?.focus();
    };

    const focusTitleUseRef = () =>
    {
        titleInputRef.current?.focus();
    };

    const handleSubmit = () =>
    {
        if(!taskTitle.trim()) return;

        onSubmit({
            title: taskTitle.trim(),
            description: description.trim(),
            priority,
            tags: parsedTags
        });

        resetForm();
        setIsExpanded(false);
    };

    const handleKeyUp = (e: React.KeyboardEvent) =>
    {
        if(e.key === 'Enter')
        {
            handleSubmit();
        }
    };

    return (
        <div className="form-wrapper">
            <button className="add-btn" onClick={toggleForm}>
                {isExpanded ? '✕ Cancel' : '+ New Task'}
            </button>

            {isExpanded && (
                <div className="form-panel">
                    <div className="form-group">
                        <label>Title *</label>
                        <input
                            ref={titleInputRef}
                            type="text"
                            placeholder="What needs to be done?"
                            value={taskTitle}
                            onChange={(e) => setTaskTitle(e.target.value)}
                            onKeyUp={handleKeyUp}
                        />
                    </div>

                    <div className="form-group">
                        <label>Description</label>
                        <textarea
                            placeholder="Add more details..."
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                        ></textarea>
                    </div>

                    <div className="form-group">
                        <label>Priority</label>
                        <div className="priority-selector">
                            <button
                                className={`priority-btn low ${priority === 'low' ? 'selected' : ''}`}
                                onClick={() => setPriority('low')}
                            >Low
                            </button>
                            <button
                                className={`priority-btn medium ${priority === 'medium' ? 'selected' : ''}`}
                                onClick={() => setPriority('medium')}
                            >Medium
                            </button>
                            <button
                                className={`priority-btn high ${priority === 'high' ? 'selected' : ''}`}
                                onClick={() => setPriority('high')}
                            >High
                            </button>
                            <button
                                className={`priority-btn urgent ${priority === 'urgent' ? 'selected' : ''}`}
                                onClick={() => setPriority('urgent')}
                            >Urgent
                            </button>
                        </div>
                    </div>

                    <div className="form-group">
                        <label>Tags (comma-separated)</label>
                        <input
                            type="text"
                            placeholder="frontend, bug, feature..."
                            value={tagsInput}
                            onChange={(e) => setTagsInput(e.target.value)}
                        />
                        {parsedTags.length > 0 && (
                            <div className="tag-preview">
                                {parsedTags.map((tag) => (
                                    <span key={tag} className="tag">{tag}</span>
                                ))}
                            </div>
                        )}
                    </div>

                    <button className="submit-btn" onClick={handleSubmit}>
                        Create Task
                    </button>
                    <button className="submit-btn" onClick={() => focusTitleTemplateRef(titleInputRef.current)}>
                        Focus Title (Callback Ref)
                    </button>
                    <button className="submit-btn" onClick={focusTitleUseRef}>
                        Focus Title (useRef)
                    </button>
                </div>
            )}
        </div>
    );
}
